### ISSUE TITLE
how to use this ? xD

### ISSUE THREAD

**Issue by dapaster** [0x44F/csgo-killwell#1]
any video?

**Comment by 0x44F** [comment]
Please stop clogging the issues up with stupid questions. If you don't know how to install python and run a python script then why are you even on GitHub? Your account is a pathetic waste of space and your name a failed attempt at a joke. 

Run along and go skid some more code, skiddie. Stop bothering other users with your absolute stupidity and go use your time to learn some actually valued skills.

Regards, 0x44F.
